trigger:
- master

pool:
  name: 'Default'  # Or whatever your agent pool is named

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
